version: '3.8'
services:
  hosting:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "3009:8080"
    container_name: hosting_affitto
    environment:
      - BACKEND_PORT=5078